pipeline:
  name: CI Intelligence Enablement Sample
  identifier: buildTurboSample
  projectIdentifier: "{{projectId}}"
  orgIdentifier: "{{orgId}}"
  tags:
    agents-library: generated
  properties:
    ci:
      codebase:
        repoName: <+input>
        build: <+input>
  stages:
    - stage:
        name: Run CI Intelligence Enablement
        identifier: Run_buildTurbo
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Agent
                  name: CI Intelligence Enablement
                  identifier: buildTurbo
                  spec:
                    agentName: buildTurbo
                    agentSettings:
                      llm_connector: <+input>
                      model_name: <+input>.default(global.anthropic.claude-opus-4-6-v1)
                      mcp_connectors: <+input>
