pipeline:
  name: IaCM Remediation Sample
  identifier: iacmRemediationAgentSample
  projectIdentifier: "{{projectId}}"
  orgIdentifier: "{{orgId}}"
  tags:
    agents-library: generated
  properties:
    ci:
      codebase:
        repoName: <+input>
        build: <+input>
  stages:
    - stage:
        name: Run IaCM Remediation
        identifier: Run_iacmRemediationAgent
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Agent
                  name: IaCM Remediation
                  identifier: iacmRemediationAgent
                  spec:
                    agentName: iacmRemediationAgent
                    agentSettings:
                      workspace: <+input>
                      llm_connector: <+input>
                      model_name: <+input>
