pipeline:
  name: Auto-Remediation Sample
  identifier: remediationAgentSample
  projectIdentifier: "{{projectId}}"
  orgIdentifier: "{{orgId}}"
  tags:
    agents-library: generated
  properties:
    ci:
      codebase:
        repoName: <+input>
        build: <+input>
  stages:
    - stage:
        name: Run Auto-Remediation
        identifier: Run_remediationAgent
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Agent
                  name: Auto-Remediation
                  identifier: remediationAgent
                  spec:
                    agentName: remediationAgent
                    agentSettings:
                      execution_id: <+pipeline.executionId>
                      account_id: <+account.identifier>
                      org_id: <+org.identifier>
                      project_id: <+project.identifier>
                      llm_connector: <+input>
                      scm_connector: <+input>
